version = 1


[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]
  style_guide = "airbnb"
  module_system = "es-modules"
  environment = [
    "nodejs",
    "browser",
    "jest"
  ]

  dialect = "typescript"